services:
  web:
    build: .
    pull_policy: build
    ports:
      - "${WEB_PORT:-8000}:8000"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - backend
    stop_signal: SIGINT
    restart: always

  postgres:
    image: postgres:17.4-alpine
    environment:
      - POSTGRES_DB=${DATABASE_NAME:-nocapcooking}
      - POSTGRES_USER=${DATABASE_USER:-nocapcooking}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD:-password}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "${DATABASE_PORT:-5432}:5432"
    networks:
      - backend
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DATABASE_USER:-nocapcooking}"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always

networks:
  backend:

volumes:
  postgres-data:
