# Generated by Django 5.1.7 on 2025-03-24 09:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cuisine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name of the cuisine (e.g., Italian)", max_length=50
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Diet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Dietary category (e.g., Omnivore, Carnivore)",
                        max_length=50,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Ingredient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name of the ingredient (e.g., Spaghetti)",
                        max_length=50,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Recipe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name of the recipe (e.g., Spaghetti Carbonara)",
                        max_length=100,
                    ),
                ),
                (
                    "recipe",
                    models.TextField(
                        help_text="Step-by-step instructions for preparing the recipe"
                    ),
                ),
                (
                    "image_path",
                    models.TextField(
                        help_text="Path for the photo of the recipe", max_length=100
                    ),
                ),
                (
                    "audio_path",
                    models.TextField(
                        help_text="Path for the audio TTS of the recipe", max_length=100
                    ),
                ),
                (
                    "cuisine",
                    models.ForeignKey(
                        help_text="Cuisine associated with the recipe",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.cuisine",
                    ),
                ),
                (
                    "diet",
                    models.ManyToManyField(
                        help_text="Dietary categories that apply to the recipe",
                        to="core.diet",
                    ),
                ),
                (
                    "ingredients",
                    models.ManyToManyField(
                        help_text="Ingredients used in the recipe", to="core.ingredient"
                    ),
                ),
            ],
        ),
    ]
