name: Build and deploy docs to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  pages: write
  id-token: write

jobs:
  build:
    name: Build documentation artifact
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build and start services
        run: |
          docker compose -f compose-dev.yaml up --build -d

      - name: Generate documentation
        run: |
          docker compose -f compose-dev.yaml exec devcontainer python generate-docs.py

      - name: Copy generated docs to host
        run: |
          docker compose -f compose-dev.yaml cp devcontainer:/app/docs .

      - name: Stop and remove services
        run: |
          docker compose -f compose-dev.yaml down --volumes

      - name: Upload docs artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs/

  deploy:
    name: Deploy docs to GitHub Pages
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
