name: Django CI Tests

on: [push]

jobs:
  run-tests:
    name: Run Django Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Prepare Environment
        run: cp .env.example .env

      - name: Run Django Tests with Docker Compose
        uses: adambirds/docker-compose-action@v1.5.0
        with:
          compose-file: "compose-dev.yaml"
          up-flags: "--build"
          down-flags: "--volumes"
          test-container: "devcontainer"
          test-command: "python manage.py test"