name: Run Django tests

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  run-tests:
    name: Run Django tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up environment file
        run: cp .env.example .env

      - name: Run Django tests
        run: |
          docker compose -f compose-dev.yaml run --rm --build devcontainer python manage.py test
